import {IOrder, orderStatuses} from "../types/order";

export const ordersData: IOrder[] = [
  { id: 101,
    orderDate: "2022-09-15",
    deliveryDate: "2022-09-16",
    status: orderStatuses.created,
    user: "John Doe",
    deliveryType: "Standard",
    servingType: "Dine-in",
    paymentType: "Credit card",
    deliveryNotification: false,
    feedbackNotification: true,
    items: [
      {
        id: 1,
        name: "Cheeseburger",
        description: "Juicy beef patty with melted cheese",
        price: 10.99,
        count: 2
      }, {
        id: 2,
        name: "French fries",
        description: "Crispy golden fries",
        price: 3.99,
        count: 1
      } ],
    total: 25.97 },
  { id: 102,
    orderDate: "2022-09-16",
    deliveryDate: "2022-09-17",
    status: orderStatuses.cooking,
    user: "Jane Smith",
    deliveryType: "Express",
    servingType: "Takeaway",
    paymentType: "Cash on delivery",
    deliveryNotification: true,
    feedbackNotification: true,
    items: [ { id: 1,
      name: "Margherita pizza",
      description: "Classic Italian pizza with tomato and mozzarella",
      price: 12.99,
      count: 1 } ],
    total: 12.99 },
  { id: 103,
    orderDate: "2022-09-17",
    deliveryDate: "2022-09-19",
    status: orderStatuses.done,
    user: "Alice Johnson",
    deliveryType: "Standard",
    servingType: "Dine-in",
    paymentType: "Online banking",
    deliveryNotification: false,
    feedbackNotification: false,
    items: [ { id: 1,
      name: "Sushi combo",
      description: "Assorted sushi rolls and sashimi",
      price: 24.99,
      count: 1 } ],
    total: 24.99 },
  { id: 104,
    orderDate: "2022-09-18",
    deliveryDate: "2022-09-18",
    status: orderStatuses.inDelivery,
    user: "Mike Brown",
    deliveryType: "Express",
    servingType: "Takeaway",
    paymentType: "Credit card",
    deliveryNotification: false,
    feedbackNotification: true,
    items: [ { id: 1,
      name: "Chicken rice bowl",
      description: "Grilled chicken with rice and vegetables",
      price: 8.99,
      count: 1 } ],
    total: 8.99 },
  { id: 105,
    orderDate: "2022-09-19",
    deliveryDate: "2022-09-20",
    status: orderStatuses.delivered,
    user: "Sarah Wilson",
    deliveryType: "Standard",
    servingType: "Dine-in",
    paymentType: "Cash on delivery",
    deliveryNotification: false,
    feedbackNotification: false,
    items: [ { id: 1,
      name: "Vegetarian salad",
      description: "Fresh mixed greens with tomatoes and cucumbers",
      price: 6.99,
      count: 1 } ],
    total: 6.99 },
];